### ISSUE TITLE
Add project membership request and approval to Activity Log

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1255]
WHO: Sylvia

Will save us time routing through web logs like we are doing for SurFlux.

**Comment by LucaCinquini** [comment]
Done. Note that we should also add a link to "Project Activity" in the left menu bar, pointing to /signal/list/project_short_name.

**Comment by murphysj** [comment]
I have added the link in the left nav bar. 

Note, the run log is throwing a bunch of errors related to this function. You may want to look at those before we call this done.

**Comment by LucaCinquini** [comment]
Some of the old buggy code about membership signals was checked into CSS branch. I removed it and I don't see any errors, please double check me.

**Comment by murphysj** [comment]
Hmmm,
I am still getting the same errors. did you commit css?

**Comment by LucaCinquini** [comment]
I just merged all those changed from level to css.
thanks, L

On Apr 14, 2016, at 2:00 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm,
I am still getting the same errors. did you commit css?

**Comment by murphysj** [comment]
verified on cu dev, closing.
